apiVersion: v1
kind: Service
metadata:
  name: {{ template "kubebox-server.fullname" . }}
  labels:
{{ include "kubebox-server.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 43200
  ports:
    - name: {{ template "kubebox-server.name" . }}
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
{{ include "kubebox-server.select-labels" . | indent 8 }}