apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "grafana.fullname" . }}-datasource
  labels:
      grafana_datasource: "true"
data:
  datasource.yml: |-
     apiVersion: 1
     datasources:
     - name: Prometheus
       type: prometheus
       access: proxy
       orgId: 1
       url: {{ template "prometheus.address" . }}
       isDefault: true
