apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "log-factory-es.fullname" . }}
  labels:
{{ include "log-factory-es.labels" . | indent 4 }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "log-factory-es.fullname" . }}
  labels:
{{ include "log-factory-es.labels" . | indent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - "services"
      - "namespaces"
      - "endpoints"
    verbs:
      - "get"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "log-factory-es.fullname" . }}
  labels:
{{ include "log-factory-es.labels" . | indent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ template "log-factory-es.fullname" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "log-factory-es.fullname" . }}
  apiGroup: ""