---
- name: apt-get install ubuntu packages
  shell: apt-get install nfs-common
  when: ansible_os_family == "Debian"
  tags:
    - nfs

- name: configure idmapd domain for nfsv4
  lineinfile:
    dest: /etc/idmapd.conf
    regexp: "^Domain"
    insertafter: "^# Domain"
    line: "Domain = {{ nfs_idmapd_domain }}"
    backup: yes
  when: nfs_idmapd_domain is defined
  tags:
    - nfs

- include: server.yml
  when: nfs_is_server

- include: client.yml
  when: nfs_is_client

