---
- name: apt-get update
  shell: apt-get update
  when: ansible_distribution == 'Ubuntu'

- name: restart cachefilesd
  service:
    name: cachefilesd
    state: restarted

- name: reboot after driver install
  reboot:
  when: install_driver.changed and not nvidia_driver_skip_reboot

- name: restart docker
  service:
    name: docker
    state: restarted
