apiVersion: v1
kind: Service
metadata:
  name: {{ template "web-portal.fullname" . }}
  labels:
{{ include "web-portal.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
    name: http
  selector:
{{ include "web-portal.select-labels" . | indent 8 }}