kind: pipeline
name: pipeline-octopus-image-factory-shield
platform:
  os: linux
  arch: amd64
steps:
#- name: test
#  image: node:10.15.0
#  commands:
#  - npm config set registry https://registry.npm.taobao.org
#  - npm install
#  - npm test
- name: containerize
  image: docker
  volumes:
#  - name: dockerlib
#    path: /var/lib/docker
  - name: dockersock
    path: /var/run/docker.sock
  - name: drone
    path: /etc/drone
  commands:
  - . /etc/drone/env.sh
  - . /etc/drone/docker_build.sh

trigger:
  event:
  - tag

volumes:
- name: dockerlib
  host:
    path: /var/lib/docker
- name: dockersock
  host:
    path: /var/run/docker.sock
- name: drone
  host:
    path: /etc/drone