---
- hosts: kube-nvidia-gpu-node
  become: true
  tasks:
    - name: install custom facts module
      include_role:
        name: facts

    - name: install nvidia-docker
      include_role:
        name: nvidia.nvidia_docker
      when:
        - ansible_local['gpus']['count'] and (ansible_distribution == "Ubuntu" or ansible_os_family == "RedHat")
        - ansible_product_name is not search("DGX-1") and ansible_product_name is not search("DGX-2")
