---
# Commented by zhangshuiyong@pcl.ac.cn

# Kubernetes Cluster Playbook
# Install python required for Ansible
- include: bootstrap-python.yml
  tags:
    - bootstrap

- include: check-and-reset-all-node-in-k8s.yml

# Install driver and container runtime on GPU servers
#- include: install-nvidia-driver.yml
#  tags:
#    - nvidia

# Install Kubernetes
# for configuration, see: config/group_vars/all.yml

- include: create-single-k8s-cluster.yml

- include: nvidia-docker.yml
  tags:
    - nvidia

# config nvidia docker
- include: config-openi-octopus-nvidia-docker.yml
  tags:
    - config-openi-octopus-nvidia-docker

# Install k8s GPU device plugin
# one cluster only install once

- hosts: kube-nvidia-gpu-node
  tasks:
    - name: Install k8s GPU device plugin
      shell: kubectl create -f 'https://raw.githubusercontent.com/NVIDIA/k8s-device-plugin/{{k8s_nvidia_gpu_device_plugin_version}}/nvidia-device-plugin.yml'
      ignore_errors: True

# label worker node
- include: label-k8s-node.yml