apiVersion: v1
kind: Service
metadata:
  name: {{ template "taskset-core.fullname" . }}
  labels:
{{ include "taskset-core.labels" . | indent 4 }}
spec:
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  selector:
{{ include "taskset-core.select-labels" . | indent 8 }}
