---
- name: ubuntu pre-install tasks
  include_tasks: ubuntu-pre-install.yml
  when: ansible_distribution == 'Ubuntu'

- name: redhat family pre-install tasks
  include_tasks: redhat-pre-install.yml
  when: ansible_os_family == 'RedHat'

- name: Manage cuDNN and NCCL packages
  package:
    name: "{{ item }}"
    state: "{{ nvidia_ml_package_state }}"
  with_items:
    - "{{ nvidia_cudnn_package_version | ternary('libcudnn7='+nvidia_cudnn_package_version, 'libcudnn7') }}"
    - "{{ nvidia_cudnn_package_version | ternary('libcudnn7-dev='+nvidia_cudnn_package_version, 'libcudnn7-dev') }}"
    - "{{ nvidia_nccl_package_version | ternary('libnccl2='+nvidia_nccl_package_version, 'libnccl2') }}"
    - "{{ nvidia_nccl_package_version | ternary('libnccl-dev='+nvidia_nccl_package_version, 'libnccl-dev') }}"
  when: ansible_os_family == "Debian"

- name: Manage cuDNN and NCCL packages
  package:
    name: "{{ item }}"
    state: "{{ nvidia_ml_package_state }}"
  with_items:
    - "{{ nvidia_cudnn_package_version | ternary('libcudnn7='+nvidia_cudnn_package_version, 'libcudnn7') }}"
    - "{{ nvidia_cudnn_package_version | ternary('libcudnn7-devel='+nvidia_cudnn_package_version, 'libcudnn7-devel') }}"
    - "{{ nvidia_nccl_package_version | ternary('libnccl='+nvidia_nccl_package_version, 'libnccl') }}"
    - "{{ nvidia_nccl_package_version | ternary('libnccl-devel='+nvidia_nccl_package_version, 'libnccl-devel') }}"
  when: ansible_os_family == "RedHat"
