---
- name: add key
  apt_key:
    url: "{{ ubuntu_nvidiaml_gpgkey }}"
    id: "{{ ubuntu_nvidiaml_keyid }}"

- name: add repo
  apt_repository:
    repo: "deb {{ ubuntu_nvidiaml_baseurl }} /"
    update_cache: yes
