apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "tasksetcontroller.fullname" . }}
spec:
  selector:
    matchLabels:
{{ include "tasksetcontroller.select-labels" . | indent 8 }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
{{ include "tasksetcontroller.labels" . | indent 8 }}
    spec:
      serviceAccountName: {{ template "tasksetcontroller.fullname" . }}
      volumes:
      - name: localtime
        hostPath:
          path: /etc/localtime
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.global.image.repository.address }}{{ .Values.global.image.repository.pathname }}/{{ .Values.image.name }}:{{ default .Chart.Version .Values.image.tag }}"
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        volumeMounts:
          - name: localtime
            mountPath: /etc/localtime
        env:
          - name: WorkerAmount
            value: "{{ .Values.common.workerAmount }}"
          - name: CacheCreationTimeoutSec
            value: "{{ .Values.common.cacheCreationTimeoutSec }}"
        resources:
{{ toYaml .Values.resources | indent 10 }}
{{- with .Values.global.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}